heat_template_version: newton

description:
    CentOS servers OpenStack installations.

resources:
  network-services:
    type: "OS::Nova::Server"
    properties:
      flavor: 8 GB General Purpose v1
      image: CentOS 7 (PVHVM)
      key_name: mykey
      name: network-services
      networks:
        - network: 00000000-0000-0000-0000-000000000000
        - network: 11111111-1111-1111-1111-111111111111
        - network: management
        - network: external
      user_data: |
        #!/bin/bash -v
        yum update -y
        yum install ntp shorewall -y

  controller:
    type: "OS::Nova::Server"
    properties:
      flavor: 8 GB General Purpose v1
      image: CentOS 7 (PVHVM)
      name: controller
      admin_pass: openstack
      networks:
        - network: management
        - network: internal
        - network: external

  compute:
    type: "OS::Nova::Server"
    properties:
      flavor: 8 GB General Purpose v1
      image: CentOS 7 (PVHVM)
      name: compute
      admin_pass: openstack
      networks:
        - network: management
        - network: internal
        - network: external

  block:
    type: "OS::Nova::Server"
    properties:
      flavor: 8 GB General Purpose v1
      image: CentOS 7 (PVHVM)
      name: block
      admin_pass: openstack
      networks:
        - network: management
        - network: internal

  block1:
    type: OS::Cinder::Volume
    properties:
      size: 75

  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: block1 }
      instance_uuid: { get_resource: block }
